
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({ ObjectFactory.class })
public interface Service1Soap {


    /**
     *
     * @param strCustName
     * @param strPasswordPDF
     * @param strEmailAddrTo
     * @param strCrdContent
     * @param strContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendEmail", action = "http://tempuri.org/SendEmail")
    @WebResult(name = "SendEmailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendEmail", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.SendEmail")
    @ResponseWrapper(localName = "SendEmailResponse", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.SendEmailResponse")
    public String sendEmail(@WebParam(name = "_strEmailAddrTo", targetNamespace = "http://tempuri.org/")
                            String strEmailAddrTo,
                            @WebParam(name = "_strPasswordPDF", targetNamespace = "http://tempuri.org/")
                            String strPasswordPDF,
                            @WebParam(name = "_strCrdContent", targetNamespace = "http://tempuri.org/")
                            String strCrdContent,
                            @WebParam(name = "_strContent", targetNamespace = "http://tempuri.org/") String strContent,
                            @WebParam(name = "_strCustName", targetNamespace = "http://tempuri.org/")
                            String strCustName);

    /**
     *
     * @param strGradeCdID
     * @param strGradeCdEN
     * @param strCustName
     * @param strPasswordPDF
     * @param strEmailAddrTo
     * @param strCrdContent
     * @param strContent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendEmailRev1", action = "http://tempuri.org/SendEmailRev1")
    @WebResult(name = "SendEmailRev1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendEmailRev1", targetNamespace = "http://tempuri.org/",
                    className = "org.tempuri.SendEmailRev1")
    @ResponseWrapper(localName = "SendEmailRev1Response", targetNamespace = "http://tempuri.org/",
                     className = "org.tempuri.SendEmailRev1Response")
    public String sendEmailRev1(@WebParam(name = "_strEmailAddrTo", targetNamespace = "http://tempuri.org/")
                                String strEmailAddrTo,
                                @WebParam(name = "_strPasswordPDF", targetNamespace = "http://tempuri.org/")
                                String strPasswordPDF,
                                @WebParam(name = "_strCrdContent", targetNamespace = "http://tempuri.org/")
                                String strCrdContent,
                                @WebParam(name = "_strContent", targetNamespace = "http://tempuri.org/")
                                String strContent,
                                @WebParam(name = "_strCustName", targetNamespace = "http://tempuri.org/")
                                String strCustName,
                                @WebParam(name = "_strGradeCdID", targetNamespace = "http://tempuri.org/")
                                String strGradeCdID,
                                @WebParam(name = "_strGradeCdEN", targetNamespace = "http://tempuri.org/")
                                String strGradeCdEN);

}
