package org.tempuri;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.4.0.2248
public class Service1SoapClient {
    public static void main(String[] args) {
        Service1 service1 = new Service1();
        Service1Soap service1Soap = service1.getService1Soap();
        // Add your code to call the desired methods.


    }
}
