
package emp.info.ws.main;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "EmpInfoWs", targetNamespace = "http://main.ws.info.emp/")
@XmlSeeAlso({ ObjectFactory.class })
public interface EmpInfoWs {


    /**
     *
     * @param request
     * @return
     *     returns emp.info.ws.main.EmpInfoResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeInfo", targetNamespace = "http://main.ws.info.emp/",
                    className = "emp.info.ws.main.GetEmployeeInfo")
    @ResponseWrapper(localName = "getEmployeeInfoResponse", targetNamespace = "http://main.ws.info.emp/",
                     className = "emp.info.ws.main.GetEmployeeInfoResponse")
    @Action(input = "http://main.ws.info.emp/EmpInfoWs/getEmployeeInfoRequest",
            output = "http://main.ws.info.emp/EmpInfoWs/getEmployeeInfoResponse")
    public EmpInfoResult getEmployeeInfo(@WebParam(name = "Request", targetNamespace = "") EmpInfoRequest request);

}
