
package emp.info.ws.main;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "EmpInfoWs", targetNamespace = "http://main.ws.info.emp/",
                  wsdlLocation =
                  "http://localhost:8080/GetEmployeeInfo/EmpInfoWs?wsdl#%7Bhttp%3A%2F%2Fmain.ws.info.emp%2F%7DEmpInfoWs")
public class EmpInfoWs_Service extends Service {

    private final static URL EMPINFOWS_WSDL_LOCATION;
    private final static WebServiceException EMPINFOWS_EXCEPTION;
    private final static QName EMPINFOWS_QNAME = new QName("http://main.ws.info.emp/", "EmpInfoWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://localhost:8080/GetEmployeeInfo/EmpInfoWs?wsdl#%7Bhttp%3A%2F%2Fmain.ws.info.emp%2F%7DEmpInfoWs");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPINFOWS_WSDL_LOCATION = url;
        EMPINFOWS_EXCEPTION = e;
    }

    public EmpInfoWs_Service() {
        super(__getWsdlLocation(), EMPINFOWS_QNAME);
    }

    public EmpInfoWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPINFOWS_QNAME, features);
    }

    public EmpInfoWs_Service(URL wsdlLocation) {
        super(wsdlLocation, EMPINFOWS_QNAME);
    }

    public EmpInfoWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPINFOWS_QNAME, features);
    }

    public EmpInfoWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpInfoWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EmpInfoWs
     */
    @WebEndpoint(name = "EmpInfoWsPort")
    public EmpInfoWs getEmpInfoWsPort() {
        return super.getPort(new QName("http://main.ws.info.emp/", "EmpInfoWsPort"), EmpInfoWs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpInfoWs
     */
    @WebEndpoint(name = "EmpInfoWsPort")
    public EmpInfoWs getEmpInfoWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.ws.info.emp/", "EmpInfoWsPort"), EmpInfoWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPINFOWS_EXCEPTION != null) {
            throw EMPINFOWS_EXCEPTION;
        }
        return EMPINFOWS_WSDL_LOCATION;
    }

}
