package emp.info.ws.main;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.4.0.2248
public class EmpInfoWsPortClient {
    public static void main(String[] args) {
        EmpInfoWs_Service empInfoWs_Service = new EmpInfoWs_Service();
        EmpInfoWs empInfoWs = empInfoWs_Service.getEmpInfoWsPort();
        // Add your code to call the desired methods.


    }
}
